name: flutter_ble_acc_example
description: BLE で ICM-42688 センサ値を取得し表示する例
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.3
  just_audio: ^0.9.36
  audioplayers: ^6.0.0
  path_provider: ^2.1.2
  csv: ^5.1.1
  fl_chart: ^0.66.0
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  azblob: ^2.0.0
  crypto: ^3.0.3
  http: ^1.2.1
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - .env
